"use client";

import { Block, Callout, CodeBlock, Formula, Pipeline, StatGrid, TagRow } from "@/components/projects/Block";
import { RippleDiagram } from "@/components/projects/Diagram";
import { motion } from "framer-motion";

export const oceanTankGlyph = (
  <svg viewBox="0 0 400 240" className="h-full w-full">
    <defs>
      <linearGradient id="ot-water" x1="0" x2="0" y1="0" y2="1">
        <stop offset="0%" stopColor="#00f0ff" stopOpacity="0.3" />
        <stop offset="100%" stopColor="#9d00ff" stopOpacity="0.1" />
      </linearGradient>
    </defs>
    <rect x={20} y={40} width={360} height={170} fill="none" stroke="#fff" strokeOpacity={0.2} strokeWidth={1.5} rx={6} />
    <path d="M20,90 Q80,80 140,90 T260,90 T380,90 L380,210 L20,210 Z" fill="url(#ot-water)" />
    <path
      d="M20,90 Q80,80 140,90 T260,90 T380,90"
      stroke="#00f0ff"
      strokeOpacity={0.4}
      strokeWidth={1}
      fill="none"
    />
    <path
      d="M20,98 Q80,90 140,98 T260,98 T380,98"
      stroke="#00f0ff"
      strokeOpacity={0.2}
      strokeWidth={0.7}
      fill="none"
    />
    {[60, 130, 220, 280, 340].map((x, i) => (
      <path
        key={i}
        d={`M${x},200 Q${x + 6},170 ${x - 4},${130 + (i % 3) * 8} Q${x - 8},${100 + (i % 2) * 6} ${x + 2},${90 + (i % 3) * 5}`}
        stroke="#5fe0a0"
        strokeOpacity={0.5}
        strokeWidth={1.5}
        fill="none"
      />
    ))}
    <ellipse cx={200} cy={205} rx={140} ry={6} fill="#3a2a18" opacity={0.6} />
  </svg>
);

export default function OceanTankContent() {
  return (
    <>
      <Block kicker="what it is" title="A glass tank you can poke" accent="cyan">
        <p>
          Ocean Tank is a self-contained 3D underwater scene rendered in real time on
          the GPU. Glass walls, kelp drifting in the current, mossy rocks on the floor,
          rain drumming the surface, sky reflecting overhead — and water that{" "}
          <em>actually behaves like water</em>. Drag your mouse across the surface and
          ripples spread outward and bounce off the glass. Crank the rain and the
          whole surface comes alive.
        </p>
        <p>
          The hard part isn&apos;t any one of these effects in isolation. It&apos;s
          getting them to coexist at 60fps in a browser. Every system has to be cheap.
        </p>
        <TagRow items={["Unity 6", "URP", "HLSL Shaders", "Custom RT", "WebGL", "Procedural Mesh"]} />
      </Block>

      <Block kicker="the heart" title="Water is two numbers per pixel, ping-ponged forever" accent="cyan">
        <p>
          The water surface is a Custom Render Texture: a GPU buffer where each pixel
          stores not colour but two numbers — <strong>height</strong> in the red
          channel, <strong>velocity</strong> in the green. Every frame a fragment
          shader reads its four neighbours and writes back what the cell should
          look like next frame.
        </p>
        <p>
          The math is the discrete 2D wave equation in relaxation form. Each cell
          looks at the average of its four neighbours and accelerates towards it,
          carrying its current velocity along — like a spring network where every
          pixel tugs on the four around it.
        </p>
        <Formula
          expr={`avg     = (right + left + up + down) * 0.25
newVel  = vel + (avg - height) * 0.5
newVel *= damping        // 0.996 — energy bleeds out
newHeight = height + newVel`}
          caption="the entire water sim, in one HLSL pass · runs every frame in Custom Render Texture.shader"
        />
        <p>
          Click on the surface? Inject a height bump:
          <code className="font-mono text-neon-cyan"> smoothstep(radius, 0, distance) × strength</code>{" "}
          gets added to <code className="font-mono">newHeight</code>. The next frame
          that bump propagates outward via the neighbour average, exactly like a real
          ripple.
        </p>
        <RippleDiagram />
      </Block>

      <Block kicker="the rig" title="Eight separate systems pretending to be one" accent="cyan">
        <p>
          The tank is procedural top to bottom — no FBX terrain, no imported water
          plane. Every visible thing is generated by code at start.
        </p>
        <Pipeline
          steps={[
            { label: "WaterTankMesh", sub: "one mesh: top water grid + four glass walls + bottom (UV2 channel marks displaceable verts)" },
            { label: "Custom Render Texture", sub: "ping-pong height/velocity texture, the heart of the sim" },
            { label: "RippleSpawner", sub: "raycasts mouse, writes UV+strength+radius into a shader uniform" },
            { label: "WaterLit shader", sub: "samples the height texture, displaces verts, refracts, foams at peaks" },
            { label: "PlanarReflection", sub: "mirrors Camera.main across the water plane, oblique-projects, renders to RT" },
            { label: "KelpStrand", sub: "generates tapered ribbon kelp with horizontal sway curve" },
            { label: "RockMesh", sub: "deforms a sphere primitive's verts via 3-octave Perlin noise" },
            { label: "GPURain", sub: "Graphics.DrawMeshInstancedProcedural — millions of rain quads, one draw call" }
          ]}
        />
        <p>
          Each system runs independently. The water sim doesn&apos;t know about kelp.
          Kelp doesn&apos;t know about reflections. Reflections don&apos;t know about
          rain. They share a scene, not a coupling — which is why you can disable any
          one of them without anything else breaking.
        </p>
      </Block>

      <Block kicker="reflections" title="Mirror the world, project it onto the surface" accent="cyan">
        <p>
          Real-time water reflections are an expensive lie. The cheapest convincing
          version is <strong>planar reflection</strong>: each frame, mirror the main
          camera across the water&apos;s y-plane, give that mirrored camera an oblique
          projection clip plane (so it can&apos;t render anything below the water), and
          render the scene into a render texture. Then the water shader samples that
          texture as if it were a sky map.
        </p>
        <Formula
          expr={`mirroredPos = mainPos
mirroredPos.y = 2 * waterHeight - mainPos.y
mirroredCam.projectionMatrix = MainCam.CalculateObliqueMatrix(plane)`}
          caption="planar mirror with oblique near plane — the standard textbook recipe"
        />
        <Callout tone="default">
          The mirrored camera renders at half resolution. You won&apos;t notice — the
          water surface is rough enough that subpixel detail is lost in the bumpmap
          anyway. Half-res reflection saves about 4ms per frame on a mid-tier GPU.
        </Callout>
      </Block>

      <Block kicker="rain" title="A million drops in one draw call" accent="cyan">
        <p>
          Naive rain: instantiate a thousand transparent quads, parent them to the
          camera, animate them in C#. CPU dies, GC dies, framerate dies. Better
          version: <code className="font-mono text-neon-cyan">Graphics.DrawMeshInstancedProcedural</code>{" "}
          — a single draw call where the GPU itself generates per-instance positions
          from a structured buffer, the vertex shader applies wind drift, the
          fragment shader does soft alpha. CPU touches a uniform buffer once, then
          gets out of the way.
        </p>
        <CodeBlock>{`// Each rain drop is two numbers: spawn time, lateral seed.
// The vertex shader does:
float t = (_Time.y - dropTime[id]) * fallSpeed;
float3 p = float3(seed.x * 30, -t, seed.y * 30) + camPos;
// Wraps when t exceeds maxFallDistance — no CPU bookkeeping.`}</CodeBlock>
      </Block>

      <Block kicker="kelp & rocks" title="Procedural geometry, no FBX in sight" accent="cyan">
        <p>
          Every kelp strand is a tapered ribbon — a mesh built at start with a sway
          curve baked into the vertex positions. The shader animates it over time,
          biased by the world Y so the tip sways more than the base. Rocks are
          spheres deformed by 3-octave Perlin noise — different seeds give different
          silhouettes, all same draw cost.
        </p>
        <StatGrid
          items={[
            { label: "Tank objects", value: "42", sub: "all procedural" },
            { label: "Kelp strands", value: "9", sub: "ribbon mesh + sway shader" },
            { label: "Rocks", value: "14", sub: "deformed spheres, unique seeds" },
            { label: "Glass walls", value: "5", sub: "single mesh + UV2 mask" },
            { label: "Water grid", value: "configurable", sub: "GridMesh.cs builds N×N" },
            { label: "Reflection RT", value: "half-res", sub: "saves ~4ms/frame" }
          ]}
        />
      </Block>

      <Block kicker="the journey" title="The fights I didn't expect" accent="pink">
        <p>
          Building a believable underwater scene in a browser turned out to be a
          parade of tiny problems, each of which seemed like a single afternoon and
          turned into a week.
        </p>
        <Callout tone="struggle">
          <strong>Reflections that &quot;worked&quot; until they didn&apos;t.</strong> Mirror
          the camera, render, sample. Looked perfect. Then I tilted the camera below
          horizontal and the reflection clipped through the water as if the world
          had folded. The fix is the oblique projection clip plane — without it the
          mirrored camera renders <em>through</em> the water plane and you get
          geometry above the surface that shouldn&apos;t exist. One Unity API call.
          Took me two days to find it.
        </Callout>
        <Callout tone="struggle">
          <strong>The water sim went unstable on touch.</strong> Big mouse drag,
          ripples spread, then suddenly the whole surface explodes into noise.
          Discrete wave simulation has a CFL stability condition — if the velocity
          coefficient is too high, the cell&apos;s next-frame value depends on
          neighbours that will themselves change too much. Fix: bring the velocity
          coefficient down to 0.5 and add a 0.996 damping factor so any energy that
          does compound bleeds out fast.
        </Callout>
        <Callout tone="struggle">
          <strong>WebGL hated my shaders three different ways.</strong> Stripped the
          unlit shader (same fix as my other projects: asset-reference materials).
          Custom Render Texture didn&apos;t initialize the first frame in WebGL, so
          the water surface was garbage data — fixed with an explicit clear texture
          on awake. And HLSL precision warnings became errors in the WebGL2 backend,
          forcing me to type half/float deliberately throughout.
        </Callout>
        <p>
          The discipline here was treating each system as standalone. Build the water
          sim, ship it, write it down. Build planar reflection, ship it, write it
          down. Build kelp, ship it, write it down. Combining them at the end was
          easy because none of them shared state. If I had built them all entangled,
          the WebGL bugs would have been impossible to isolate.
        </p>
      </Block>

      <Closing accent="cyan" />
    </>
  );
}

function Closing({ accent }: { accent: "cyan" | "pink" | "lime" | "purple" }) {
  const color = { cyan: "#00f0ff", pink: "#ff2bd6", lime: "#b6ff00", purple: "#9d00ff" }[accent];
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      transition={{ duration: 0.8 }}
      className="mt-24 text-center"
    >
      <motion.div
        animate={{ opacity: [0.4, 1, 0.4] }}
        transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
        className="mx-auto mb-4 h-px w-32"
        style={{
          background: `linear-gradient(90deg, transparent, ${color}, transparent)`
        }}
      />
      <p className="font-mono text-[10px] uppercase tracking-[0.4em] text-white/40">
        end of breakdown
      </p>
    </motion.div>
  );
}
